### ISSUE TITLE
Channel Churn Rate higher on 2.0.1 compared to 1.0.0

### ISSUE THREAD

**Issue by orlandothoeny** [cloudamqp/amqproxy#169]
I upgraded from 1.0.0 to 2.0.1 today.

After the upgrade, we observe way higher channel churn rates than before.
As you can see in the graph below. The new AMQProxy version was deployed ad 11:38.
![rabbitmq-metrics-after-v2-upgrade](https://github.com/user-attachments/assets/706f63a6-a219-446b-8651-02cf32f0eb9e)

Is this expected or is there a bug somewhere?

**Comment by kickster97** [comment]
The main difference with V2.0.1 compared to v1.x is that channels are pooled, multiple client channels are shared on a single upstream connection. This will decrease the number of upstream connections needed, but will give you a higher channel churn.

**Comment by orlandothoeny** [comment]
@kickster97 Alright. Yes I see that we now have a single connection per AMQProxy instance (top left graph). Which is expected.

The channel churn rate is way higher compared to the connection churn rate (which is now 0) we previously had.
Is this normal? Won't this result in higher CPU usage on our RabbitMQ nodes?

**Comment by kickster97** [comment]
Yes, a higher channel churn will affect the cpu usage, however since the connection churn goes down it should not be too bad. You should be able to see the cpu metrics for your cluster above the metrics you have attached to this issue. If you want me to look closer at the CPU metrics you can send an email to support@cloudamqp.com with more specific details on your cluster.

**Comment by orlandothoeny** [comment]
The CPU usage looks fine to me. Just wanted to make sure this is as expected, since we had a CPU usage issue on an 2.x alpha version due to high churn, and had to roll it back to 1.x
Thanks for checking :+1:
