### ISSUE TITLE
TLS Support

### ISSUE THREAD

**Issue by BenSlabbert** [cloudamqp/amqproxy#45]
Hello,

I did some testing and it does not seem like the proxy supports TLS?
My RabbitMQ server is configured to verify peer certificates and I get the following error:

`read tcp 127.0.0.1:47624->127.0.0.1:5673: read: connection reset by peer`

which is expected if the peer is not presenting a certificate.

**Comment by carlhoerberg** [comment]
Ok, yeah, amqproxy doesn't support TLS on the listener side, so that's why you're getting connection reset by peer (the server doesn't regonize the TLS speak). But even if amqproxy could accept TLS client connections it won't be able to forward the client certificate, it's a use case no proxy can support. If you want to use a proxy you need to disable client certificate verification on the server and just use AMQPS and normal username/passwords, and in the client connect with plain AMQP to amqproxy.
