### ISSUE TITLE
ClientProvidedName

### ISSUE THREAD

**Issue by CarlosYwassa** [cloudamqp/amqproxy#61]
Hi, I configurated `ClientProvidedName`, but when I checked at rabbit the `connection_name` is empty or null and doesn't appear at client property, in attachment the problem. Can anyone help me?
![image](https://user-images.githubusercontent.com/84246169/145817418-915e448a-8481-4bd6-b448-dd5fb9e86da5.png)

**Comment by carlhoerberg** [comment]
It's because the proxy will open a connection that will be reused. So yes I guess the first connection could take the name from the client, but when the next client connects to the proxy the connection to the server will be reused and the client name can't be changed on an existing connection. Hence it doesn't make sense to consider the clients connection name.
