### ISSUE TITLE
Debian 10 - Upgrading replaces service file so requires manual changes after patching

### ISSUE THREAD

**Issue by madhancock** [cloudamqp/amqproxy#89]
We recently upgraded from 0.5.6 to 0.7.0.

This upgrade apparently replaced the `/etc/systemd/system/amqproxy.service` file which needs to be modified to include the target rabbitmq service which subsequently turned maintenance into an outage.

I can see there's some level of .ini support but it's not documented in the readme file and it's unclear without actually using it how it behaves with the .service file. E.g. does it override the defaults included in the service file? - If it doesn't then if the service file is reset the ini file isn't going to protect the configuration state.

**Comment by carlhoerberg** [comment]
For changes to the service file you should create an override.conf, preferably using `systemctl edit amqproxy`, that will not be overwritten by any packet changes/upgrades.

**Comment by timothyclarke** [comment]
@carlhoerberg I've just installed `0.8.1-1` from package cloud per the readme and the systemd service still has `ExecStart=/usr/bin/amqproxy -p 5673 amqp://127.0.0.1:5672` 

There is an [example service](https://github.com/cloudamqp/amqproxy/blob/main/extras/amqproxy.service) and [example config](https://github.com/cloudamqp/amqproxy/blob/main/config/example.ini) can we get that in the deb package (with the ini tagged as a config file) instead of the `override.conf` method above ?

**Comment by carlhoerberg** [comment]
Yes, will come with the next release.

**Comment by timothyclarke** [comment]
@carlhoerberg If the next release is going to be a while away, is there any chance of getting `0.8.1-2` with the systemd changes sooner ?

**Comment by carlhoerberg** [comment]
Available in the Artifacts here: https://github.com/cloudamqp/amqproxy/actions/runs/3544098825
